### PR TITLE
feat: add `react-native-web` support

### PR DESCRIPTION
**Pull request by t4bby**
Since `SecureStore` is not supported on the `web`, I have added `AsyncStorage` from https://react-native-async-storage.github.io/async-storage/ as an alternative.

### CODE REVIEW

**Comment by t4bby** [comment]
Marking as a `draft`, the pull request got all messed up with my fork continuing to be merged with this pull request. Using I am using `axios` instead of `fetch`. Since `fetch` causes tons of `CORS error` on `web`. 

Edit:
Reverted to the original PR.

**Comment by Tschucki** [comment]
Thanks for the pull request! 
Appreciate your contribution!

I'd like to maintain the use of SecureStorage on mobile for handling sensitive data due to its specialized encryption features, which are crucial for protecting sensitive user information in my opinion.

But we could make it compatible with web Expo by using AsyncStorage for web and sticking with SecureStorage for mobile. 
This way, we balance security and cross-platform needs.

We just had to use a different tokenstorage service for web platform and add the build-web job to the ci.

**Comment by t4bby** [comment]
It has a platform-specific implementation on the `PR`.
`TokenStorage.native.ts` - This contains code for `native (android/ios)` which still uses `SecureStorage`
`TokenStorage.ts` - For `web` that uses `AsyncStorage`

**Comment by Tschucki** [comment]
Please merge the new [Commit](https://github.com/Tschucki/react-native-laravel-sanctum/commit/6d6f9bf7c83906076876174efea5bea5a3a013f7) from the main branch and let the checks pass.

Then I will merge it.

**Comment by t4bby** [comment]
I've merged the commit

**Review by Tschucki — APPROVED** [review]

**Pull request merged**
